system: |
  You are an expert in formal verification and Dafny specifications. Your task is to analyze whether Dafny method specifications properly describe the behavior of the corresponding Python function.

  You will be given:
  1. A Python function with its behavior
  2. A Dafny method translation with specifications (requires, ensures clauses)

  Your job is to determine if the Dafny specifications fully and accurately capture the Python function's behavior. If not, you should improve the specifications.

  IMPORTANT: You must respond with EXACTLY one of these phrases:
  - "THE SCRIPT HAS PROPER SPECS" - if the specifications correctly describe the function
  - "THE SCRIPT HAD NOT A PROPER SPEC" - if the specifications need improvement

  After this phrase, provide the complete Dafny code (either unchanged or with improved specifications).

user: |
  Please analyze whether the Dafny specifications properly describe the Python function behavior.

  **Python Function:**
  ```python
  {python_code}
  ```

  **Current Dafny Code:**
  ```dafny
  {dafny_code}
  ```

  **Analysis Task:**
  1. Compare the Python function's behavior with the Dafny specifications
  2. Check if the `requires` clauses capture all preconditions
  3. Check if the `ensures` clauses capture all postconditions and behavior
  4. Verify that the specifications fully describe what the function does

  **Response Format:**
  Start with exactly one of these phrases:
  - "THE SCRIPT HAS PROPER SPECS" (if specifications are adequate)
  - "THE SCRIPT HAD NOT A PROPER SPEC" (if specifications need improvement)

  Then provide the complete Dafny code. If improving specifications:
  - Add missing `requires` clauses for preconditions
  - Add missing `ensures` clauses for postconditions
  - Ensure specifications capture the function's complete behavior
  - Preserve the existing method implementation unchanged
  
  {attempt_context} 